name: Save Streamlit Data

on:
  push:
    branches:
      - main

jobs:
  save_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Save data
        run: |
          # Hier den Befehl einfügen, um die Daten aus der Streamlit-App zu extrahieren und in das private Repository zu speichern
          # Zum Beispiel:
          python save_data_script.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update data"
          git push

